'use strict';

const { getDb, startRun, endRun } = require('./db');
const fs = require('fs');
const path = require('path');

async function run() {
  const runId = startRun('summary');
  const db = getDb();

  const now = new Date().toISOString();

  const recentRuns = db.prepare(`
    SELECT script, status, items_processed, summary, errors,
           datetime(started_at, 'unixepoch') as started,
           datetime(finished_at, 'unixepoch') as finished
    FROM runs
    WHERE started_at >= strftime('%s', datetime('now', '-24 hours'))
    ORDER BY started_at DESC
  `).all();

  const topIdeas = db.prepare(`
    SELECT niche, source_count, confidence, status
    FROM ideas
    ORDER BY confidence DESC, source_count DESC
    LIMIT 5
  `).all();

  const shortlistPath = path.join(__dirname, '..', 'data', 'shortlist.json');
  let shortlist = [];
  if (fs.existsSync(shortlistPath)) {
    try {
      shortlist = JSON.parse(fs.readFileSync(shortlistPath, 'utf8'));
    } catch (_) {}
  }

  const emailStats = db.prepare(`
    SELECT
      COUNT(*) as total_sent,
      COUNT(CASE WHEN opened_at IS NOT NULL THEN 1 END) as total_opened
    FROM email_sends
    WHERE sent_at >= strftime('%s', date('now', '-7 days'))
  `).get();

  const todaySent = db.prepare(`
    SELECT COUNT(*) as count FROM email_sends
    WHERE sent_at >= strftime('%s', date('now'))
  `).get().count;

  const totalLeads = db.prepare(`SELECT COUNT(*) as count FROM leads`).get().count;
  const newLeads = db.prepare(`SELECT COUNT(*) as count FROM leads WHERE status = 'new'`).get().count;

  const redditCount = db.prepare(`SELECT COUNT(*) as count FROM reddit_posts`).get().count;
  const hnCount = db.prepare(`SELECT COUNT(*) as count FROM hn_posts`).get().count;
  const keywordCount = db.prepare(`SELECT COUNT(*) as count FROM keywords`).get().count;
  const ideaCount = db.prepare(`SELECT COUNT(*) as count FROM ideas`).get().count;
  const validatedCount = db.prepare(`SELECT COUNT(*) as count FROM ideas WHERE status = 'validated'`).get().count;

  const openRatePct = emailStats.total_sent > 0
    ? Math.round((emailStats.total_opened / emailStats.total_sent) * 100)
    : 0;

  let md = `# autoBusiness — Run Summary\n\n`;
  md += `**Last updated:** ${now}\n\n`;
  md += `---\n\n`;

  md += `## 📊 Database Stats\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| Reddit posts scraped | ${redditCount} |\n`;
  md += `| HackerNews posts scraped | ${hnCount} |\n`;
  md += `| Keywords tracked | ${keywordCount} |\n`;
  md += `| Ideas scored | ${ideaCount} |\n`;
  md += `| Ideas validated | ${validatedCount} |\n`;
  md += `| Total leads | ${totalLeads} |\n`;
  md += `| Leads ready to email | ${newLeads} |\n\n`;

  md += `## 📧 Email Stats (Last 7 Days)\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Emails sent | ${emailStats.total_sent} |\n`;
  md += `| Emails opened | ${emailStats.total_opened} |\n`;
  md += `| Open rate | ${openRatePct}% |\n`;
  md += `| Sent today | ${todaySent} |\n\n`;

  md += `## 🏆 Top Ideas by Convergence Score\n\n`;
  if (topIdeas.length > 0) {
    md += `| Niche | Sources | Confidence | Status |\n`;
    md += `|-------|---------|------------|--------|\n`;
    for (const idea of topIdeas) {
      md += `| ${idea.niche} | ${idea.source_count} | ${Math.round((idea.confidence || 0) * 100)}% | ${idea.status} |\n`;
    }
  } else {
    md += `_No ideas scored yet. Run the scrapers and idea-scorer._\n`;
  }
  md += `\n`;

  if (shortlist.length > 0) {
    md += `## ✅ Validated Shortlist\n\n`;
    for (const item of shortlist.filter(i => i.status === 'validated').slice(0, 5)) {
      md += `- **${item.niche}** — ${item.source_count} sources (${item.sources.join(', ')}), confidence: ${item.confidence}%\n`;
    }
    md += `\n`;
  }

  md += `## 🕒 Recent Runs (Last 24h)\n\n`;
  if (recentRuns.length > 0) {
    md += `| Script | Status | Items | Started |\n`;
    md += `|--------|--------|-------|---------|\n`;
    for (const run of recentRuns) {
      const statusEmoji = run.status === 'success' ? '✅' : run.status === 'partial' ? '⚠️' : '❌';
      md += `| ${run.script} | ${statusEmoji} ${run.status} | ${run.items_processed} | ${run.started} |\n`;
    }
  } else {
    md += `_No runs in the last 24 hours._\n`;
  }
  md += `\n`;

  const errorRuns = recentRuns.filter(r => r.errors);
  if (errorRuns.length > 0) {
    md += `## ⚠️ Errors\n\n`;
    for (const run of errorRuns) {
      md += `**${run.script}:** ${run.errors}\n\n`;
    }
  }

  md += `---\n`;
  md += `_Generated by autoBusiness — [GitHub Actions](../../actions)_\n`;

  const dataDir = path.join(__dirname, '..', 'data');
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(path.join(dataDir, 'summary.md'), md);

  console.log('[summary] Summary written to data/summary.md');
  console.log(md);

  endRun(runId, 'success', 1, 'Summary generated.', null);
}

run().catch(err => {
  console.error('[summary] Fatal error:', err);
  process.exit(1);
});
